version: "3.9"
services:
  db:
    image: postgres:14.2
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: vVBQ7pgHHF4x
      POSTGRES_DB: delivery
    volumes:
      - "dbdata:/var/lib/postgresql/data"
    ports:
      - "5432:5432"

volumes:
  dbdata: